# Generated by Django 5.2.5 on 2025-09-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_date_of_birth_author_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto del autor', null=True, upload_to='authors/'),
        ),
    ]
