# Generated by Django 5.2.5 on 2025-09-04 03:16

import apps.authors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_author_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto del autor', null=True, upload_to=apps.authors.models.get_author_photo_upload_path),
        ),
    ]
