services:
  redis:
    image: redis:7-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  backend:
    environment:
      USE_CACHE: "true"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      redis:
        condition: service_started

volumes:
  redis_data:
