services:
  db:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_review
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/book_review
      USE_CACHE: "false"
      USE_REVERSE_PROXY: "true"
      AUTHOR_PHOTOS_UPLOAD_PATH: "authors/"
      BOOK_COVERS_UPLOAD_PATH: "books/"
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"
    restart: unless-stopped
    volumes:
      - .:/app
      - static_data:/app/static
      - media_data:/app/media

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_data:/app/static
      - media_data:/app/media
    depends_on:
      - backend

volumes:
  postgres_data:
  static_data:
  media_data:
