# Generated by Django 5.2.5 on 2025-09-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_name_alter_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagen de portada del libro', null=True, upload_to='books/'),
        ),
    ]
