# Generated by Django 5.2.5 on 2025-09-08 03:23

import apps.books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagen de portada del libro', null=True, upload_to=apps.books.models.get_book_cover_upload_path),
        ),
    ]
