# Generated by Django 5.2.5 on 2025-08-13 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('score', models.PositiveSmallIntegerField()),
                ('up_votes', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book')),
            ],
            options={
                'ordering': ['-up_votes', '-score'],
                'indexes': [models.Index(fields=['book', 'score'], name='reviews_rev_book_id_05cf8c_idx'), models.Index(fields=['up_votes'], name='reviews_rev_up_vote_9eead1_idx')],
            },
        ),
    ]
